version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres-db:
    image: postgres:16-alpine
    container_name: lifebit_postgres_prod
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./LifeBit.sql:/docker-entrypoint-initdb.d/01-lifebit.sql:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-lifebit_db}
      - POSTGRES_USER=${POSTGRES_USER:-lifebit_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-lifebit_password}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
      - TZ=Asia/Seoul
    restart: unless-stopped
    networks:
      - lifebit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-lifebit_user} -d ${POSTGRES_DB:-lifebit_db}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Core API (Spring Boot)
  core-api:
    build:
      context: ./apps/core-api-spring
      dockerfile: Dockerfile
    container_name: lifebit_core_api_prod
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/${POSTGRES_DB:-lifebit_db}?stringtype=unspecified
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-lifebit_user}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-lifebit_password}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lifebit-network
    volumes:
      - ./uploads:/app/uploads
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # AI API (FastAPI)
  ai-api:
    build:
      context: ./apps/ai-api-fastapi
      dockerfile: Dockerfile
    container_name: lifebit_ai_api_prod
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-lifebit_user}:${POSTGRES_PASSWORD:-lifebit_password}@postgres-db:5432/${POSTGRES_DB:-lifebit_db}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - USE_GPT=${USE_GPT:-False}
      - CORS_ORIGINS=http://localhost:3000,http://${DOMAIN_NAME:-localhost}:3000,http://${DOMAIN_NAME:-localhost},http://${DOMAIN_NAME:-localhost}:80
      - PORT=8001
      - HOST=0.0.0.0
    ports:
      - "8001:8001"
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - lifebit-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  # Frontend (React)
  frontend:
    build:
      context: ./apps/frontend-vite
      dockerfile: Dockerfile
      args:
        - VITE_CORE_API_URL=http://${DOMAIN_NAME:-localhost}:8080
        - VITE_AI_API_URL=http://${DOMAIN_NAME:-localhost}:8001
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID:-}
        - VITE_KAKAO_CLIENT_ID=${VITE_KAKAO_CLIENT_ID:-}
    container_name: lifebit_frontend_prod
    ports:
      - "3000:80"
    depends_on:
      - core-api
      - ai-api
    restart: unless-stopped
    networks:
      - lifebit-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    container_name: lifebit_nginx_prod
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - core-api
      - ai-api
    restart: unless-stopped
    networks:
      - lifebit-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  lifebit-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
    driver: local 