services:
  # PostgreSQL 데이터베이스
  postgres-db:
    image: postgres:16
    container_name: lifebit_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=lifebit_db
      - POSTGRES_USER=lifebit_user
      - POSTGRES_PASSWORD=lifebit_password
    ports:
      - "5432:5432"
    restart: always
    networks:
      - lifebit-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lifebit_user -d lifebit_db"]
      interval: 30s
      timeout: 10s
      retries: 3