global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'spring-boot'
    static_configs:
      - targets: ['spring-api:8080']
    metrics_path: '/actuator/prometheus'

  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:8001']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-db:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-cache:6379'] 