---
# 프로젝트 기본 설정
project_name: "lifebit"
project_path: "/opt/lifebit"

# 클라우드 프로바이더 설정
cloud_provider: "aws"
aws_region: "ap-northeast-2"
instance_type: "t3.small"

# Git 저장소 설정
git_repository_url: "https://github.com/Hyeon6492/LifeBit.git"  # 실제 저장소 URL로 변경
git_branch: "main"

# OpenAI API 설정 (대문자로 통일)
OPENAI_API_KEY: "{{ vault_openai_api_key | default('your-api-key-here') }}"
USE_GPT: "False"

# OAuth 설정 (대문자로 통일)
KAKAO_CLIENT_ID: "YOUR_KAKAO_CLIENT_ID"
KAKAO_REDIRECT_URI: ""

GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID"
GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET"
GOOGLE_REDIRECT_URI: ""

# PostgreSQL 데이터베이스 설정 (대문자로 통일)
POSTGRES_DB: "lifebit_db"
POSTGRES_USER: "lifebit_user"
POSTGRES_PASSWORD: "{{ vault_db_password | default('lifebit_password') }}"
POSTGRES_HOST: "postgres-db"  # Docker Compose 서비스명
POSTGRES_PORT: "5432"

# 기존 호환성을 위한 소문자 변수
postgres_db: "{{ POSTGRES_DB }}"
postgres_user: "{{ POSTGRES_USER }}"
postgres_password: "{{ POSTGRES_PASSWORD }}"
db_name: "{{ POSTGRES_DB }}"
db_user: "{{ POSTGRES_USER }}"
db_password: "{{ POSTGRES_PASSWORD }}"

# Redis 설정 (대문자로 통일)
REDIS_PASSWORD: "{{ vault_redis_password | default('redis_password') }}"

# JWT 설정 (대문자로 통일)
JWT_SECRET: "{{ vault_jwt_secret | default('your-jwt-secret-key-here') }}"
JWT_SECRET_KEY: "{{ vault_jwt_secret_key | default('your-jwt-secret-key-here') }}"
JWT_ALGORITHM: "HS256"

# CORS 설정 (대문자로 통일)
CORS_ORIGINS: "*"

# 로그 레벨 (대문자로 통일)
LOG_LEVEL: "info"

# Airflow 설정 (대문자로 통일)
AIRFLOW_ADMIN_USER: "admin"
AIRFLOW_ADMIN_PASSWORD: "{{ vault_airflow_password | default('admin_password') }}"
AIRFLOW_FERNET_KEY: "{{ vault_airflow_fernet_key | default('your-fernet-key-here') }}"

# Grafana 설정 (대문자로 통일)
GRAFANA_ADMIN_USER: "admin"
GRAFANA_ADMIN_PASSWORD: "{{ vault_grafana_password | default('admin_password') }}"

# 모니터링 설정
enable_monitoring: true
backup_retention_days: 7

# 보안 설정
allowed_ssh_sources:
  - "0.0.0.0/0"  # 프로덕션에서는 제한적으로 설정

# 성능 설정
max_upload_size: "100M"
worker_processes: "auto"

# 로깅 설정
log_retention_days: 30

# AWS 특화 설정
aws_ebs_optimized: false
aws_monitoring: false 