# 개발 환경 설정
spring:
  jpa:
    hibernate:
      ddl-auto: none  # Flyway 사용으로 통일
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  
  # 개발 환경에서 Flyway 활성화
  flyway:
    enabled: true
    clean-disabled: false  # 개발 환경에서는 clean 허용
    baseline-on-migrate: true
        
# 개발용 로깅 설정
logging:
  level:
    com.lifebit: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG 