name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # 최신 버전 사용 가능

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./infrastructure/terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./infrastructure/terraform

      - name: Get instance public IP
        id: get_ip
        run: echo "INSTANCE_IP=$(terraform output -raw instance_public_ip)" >> $GITHUB_ENV
        working-directory: ./infrastructure/terraform

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/lifebit-key.pem
          chmod 600 ~/.ssh/lifebit-key.pem

      - name: Update Ansible inventory
        run: echo "[servers]\n${{ env.INSTANCE_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/lifebit-key.pem" > infrastructure/ansible/inventory
        
      - name: Wait for SSH to be available
        run: |
          for i in {1..30}; do
            if ssh -o StrictHostKeyChecking=no -i ~/.ssh/lifebit-key.pem ubuntu@${{ env.INSTANCE_IP }} 'echo "SSH is ready"'; then
              break
            fi
            echo "Waiting for SSH connection... ($i/30)"
            sleep 10
          done

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook playbook.yml
        working-directory: ./infrastructure/ansible 